version: '3.8'
services:
  frontend:
    image: naqz05/fis_2610_3517_g1-frontend:latest
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      app-network:
        ipv4_address: 172.20.0.2

  backend:
    image: naqz05/fis_2610_3517_g1-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      app-network:
        ipv4_address: 172.20.0.3

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:
    name: fis_2610_3517_g1_mongo_data

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16