sonar.projectKey=puj-course_FIS_2610_3517_G1
sonar.organization=puj-course

sonar.sources=backend,frontend
sonar.tests=tests

sonar.exclusions=**/__pycache__/**,.venv/**,backend/venv/**,**/.pytest_cache/**,**/*.db,database.db,backend/database.db,**/node_modules/**,**/dist/**,**/build/**,frontend/registro_medicamento.txt

sonar.coverage.exclusions=tests/**,frontend/**,backend/seed.py,backend/main.py,backend/__init__.py,backend/**/__init__.py

sonar.cpd.exclusions=frontend/**/*.html,frontend/**/*.HTML,frontend/registro_medicamento.txt

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
