sonar.projectKey=puj-course_FIS_2610_3517_G1
sonar.organization=puj-course
sonar.host.url=https://sonarcloud.io

# Analizar solo backend útil del proyecto
sonar.sources=backend
sonar.tests=tests

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8

# Archivos/carpetas excluidas totalmente del análisis de Sonar
sonar.exclusions=frontend/**,docs/**,htmlcov/**,coverage.xml,.coverage,**/__pycache__/**,**/.pytest_cache/**,.venv/**,venv/**,backend/venv/**,**/database.db,**/*.db,**/build-wrapper-dump.json,backend/models.py,backend/routes/historial_route.py,backend/routes/auth_route.py,backend/middleware/auth_middleware.py

# Archivos excluidos solo del cálculo de cobertura
sonar.coverage.exclusions=tests/**,frontend/**,docs/**,backend/seed.py,backend/main.py,backend/__init__.py,backend/**/__init__.py,backend/models.py,backend/routes/historial_route.py,backend/routes/auth_route.py,backend/middleware/auth_middleware.py

# Excluir duplicación de frontend y docs
sonar.cpd.exclusions=frontend/**,docs/**