sonar.projectKey=puj-course_FIS_2610_3517_G1
sonar.organization=puj-course
sonar.host.url=https://sonarcloud.io

sonar.sources=backend,frontend
sonar.tests=tests

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/__pycache__/**,**/.pytest_cache/**,.venv/**,backend/venv/**,**/database.db,**/*.db,coverage.xml,htmlcov/**

sonar.coverage.exclusions=tests/**,frontend/**,backend/seed.py,backend/main.py,backend/__init__.py,backend/**/__init__.py

sonar.cpd.exclusions=frontend/**/*.html,frontend/**/*.HTML
