name: CD - Build & Deploy Docker Image

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  docker-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: fis_2610_3517_g1-backend
            context: .
            is_backend: true
          - image: fis_2610_3517_g1-frontend
            context: ./medtrack-app
            is_backend: false

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Login a DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y Push Backend
        if: matrix.is_backend == true
        run: |
          docker build \
            --build-arg TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }} \
            --build-arg TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }} \
            --build-arg TWILIO_FROM=${{ secrets.TWHILIO_FROM }} \
            --build-arg MONGO_URI=${{ secrets.MONGO_URI }} \
            --build-arg SECRET_KEY=${{ secrets.SECRET_KEY }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest \
            -f ${{ matrix.context }}/Dockerfile \
            ${{ matrix.context }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest

      - name: Build y Push Frontend
        if: matrix.is_backend == false
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest \
            -f ${{ matrix.context }}/Dockerfile \
            ${{ matrix.context }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest